name: CI Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - 'gitbook/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'gitbook/**'

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workers: [4]  # Optional: Test different worker counts
    permissions:
      contents: write  # Needed to push reports to the repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --output-path=dist/angular-portfolio-app

      - name: Verify build output
        run: |
          ls -la dist/angular-portfolio-app
          ls -la dist/angular-portfolio-app/browser

      - name: Install Playwright
        run: |
          npx playwright install --with-deps
          npx playwright install-deps

      - name: Run Playwright tests
        run: npx playwright test --workers=4 tests
        env:
          CI: true

      - name: Upload and manage test reports in repo
        if: always()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Debug directory structure
          echo "Current directory structure:"
          ls -R playwright-report

          # Create report directory
          REPORT_DIR="ci_reports/$(date +%Y%m%d_%H%M%S)_${{ github.run_id }}"
          mkdir -p $REPORT_DIR
          cp -r playwright-report/* $REPORT_DIR/

          # Enhanced trace handling
          TRACE_SOURCE="playwright-report/trace"
          if [ -d "$TRACE_SOURCE" ]; then
            echo "Zipping trace directory from root location"
            zip -r $REPORT_DIR/trace.zip "$TRACE_SOURCE"
          elif [ -d "playwright-report/data/trace" ]; then
            echo "Zipping trace directory from data/trace location"
            zip -r $REPORT_DIR/trace.zip playwright-report/data/trace
          elif [ -f "playwright-report/trace.zip" ]; then
            echo "Copying existing trace.zip"
            cp playwright-report/trace.zip $REPORT_DIR/
          else
            echo "No trace files found"
          fi

          # Cleanup old reports
          cd ci_reports
          directories=$(ls -td */ 2>/dev/null | sed 's#/##g')
          if [ -n "$directories" ]; then
            count=$(echo "$directories" | wc -l)
            if [ $count -gt 5 ]; then
              to_delete=$(echo "$directories" | tail -n +6)
              echo "Removing old reports: $to_delete"
              rm -rf $to_delete
            fi
          fi

          # Commit and push changes
          git add .
          git commit -m "CI: Update test reports $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Netlify
        if: success()
        run: |
          curl -X POST -d {} ${{ secrets.NETLIFY_HOOK_URL }}
