name: Playwright and Netlify Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
    
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build Angular app
      - name: Build Angular app
        run: npm run build

      # Step 5: Serve Angular app in the background
      - name: Serve Angular app in background
        run: |
          npx http-server ./dist/portfolio -p 4200 &
        env:
          CI: true

      # Step 6: Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test tests --reporter=html

      # Step 7: Upload test reports
      - name: Upload Playwright test reports
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Step 8: Trigger Netlify deployment if tests pass
      - name: Trigger Netlify deployment
        if: success()
        run: |
          curl -X POST -d {} ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
