name: Playwright CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Playwright Tests on localhost
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build Angular app
        run: npm run build

      - name: Serve Angular app in background
        run: |
          npx http-server ./dist/portfolio -p 4200 &
        env:
          CI: true

      - name: Wait for local server
        run: |
          for i in {1..20}; do
            curl -sSf http://localhost:4200 && break || sleep 3
          done

      - name: Run Playwright tests
        run: npx playwright test tests
        env:
          BASE_URL: http://localhost:4200

      - name: Upload HTML report if tests failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  deploy:
    name: Deploy to Netlify if tests pass
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Trigger Netlify webhook
        run: curl -X POST "${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}"

      - name: Wait for Netlify deploy to be live
        run: |
          for i in {1..20}; do
            curl -sSf https://skansen.netlify.app && break || sleep 5
          done
