name: Playwright Tests with Netlify Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Build the Angular app
      - name: Build Angular app
        run: npm run build

      # Serve the built Angular app locally
      - name: Serve Angular app in background
        run: |
          npx http-server ./dist/portfolio -p 4200 &
        env:
          CI: true    

      # Get the local IP address dynamically (this is usually 127.0.0.1 in most CI environments)
      - name: Get local server IP address
        id: get-ip
        run: echo "::set-output name=ip::$(hostname -I | awk '{print $1}')"

      # Wait for the local server to be available
      - name: Wait for local server to be available
        run: |
          for i in {1..20}; do
            curl -sSf http://${{ steps.get-ip.outputs.ip }}:4200/index.html && break || sleep 3
          done

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test tests
        continue-on-error: true

      # If tests pass, deploy to Netlify
      - name: Deploy to Netlify
        if: success()
        run: |
          curl -X POST https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK }}

      # If tests fail, upload the Playwright test report
      - name: Upload Playwright Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
