name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push reports to the repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get git history for proper branch handling
          persist-credentials: true  # Required to push changes back

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --output-path=dist/angular-portfolio-app

      - name: Verify build output
        run: |
          ls -la dist/angular-portfolio-app
          ls -la dist/angular-portfolio-app/browser

      - name: Install Playwright
        run: |
          npx playwright install --with-deps
          npx playwright install-deps

      - name: Run Playwright tests
        run: npx playwright test tests
        env:
          CI: true

      - name: Upload and manage test reports in repo
        if: always()  # Upload even if previous steps failed
        run: |
          # Configure git user
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Create report directory with timestamp and run ID
          REPORT_DIR="ci_reports/$(date +%Y%m%d_%H%M%S)_${{ github.run_id }}"
          mkdir -p $REPORT_DIR
          cp -r playwright-report/* $REPORT_DIR/

          # Remove oldest reports if more than 5
          cd ci_reports
          # List directories sorted by creation time (newest first)
          directories=$(ls -td */ 2>/dev/null | sed 's#/##g')
          if [ -n "$directories" ]; then
            # Count directories and delete if more than 5
            count=$(echo "$directories" | wc -l)
            if [ $count -gt 5 ]; then
              to_delete=$(echo "$directories" | tail -n +6)
              echo "Removing old reports: $to_delete"
              rm -rf $to_delete
            fi
          fi

          # Commit and push changes
          git add .
          git commit -m "CI: Update test reports $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatic token with repo access

      - name: Deploy to Netlify
        if: success()
        run: |
          curl -X POST -d {} ${{ secrets.NETLIFY_HOOK_URL }}
