name: CI with Playwright and Netlify

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        id: test
        continue-on-error: true
        run: |
          npx playwright test tests --reporter=html

      - name: Upload HTML report if tests fail
        if: steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/

      - name: Trigger Netlify Deploy
        if: steps.test.outcome == 'success'
        run: |
          curl -X POST "${{ secrets.NETLIFY_HOOK_URL }}"
